### ISSUE TITLE
Strange image & real factor calculation in SO3::expAndTheta function

### ISSUE THREAD

**Issue by Mikhail2017** [strasdat/Sophus#108]
In case of small omega you are using next code:

```
if ((*theta) < Constants<Scalar>::epsilon()) 
{
      Scalar theta_po4 = theta_sq * theta_sq;
      imag_factor = Scalar(0.5) - Scalar(1.0 / 48.0) * theta_sq +
                    Scalar(1.0 / 3840.0) * theta_po4;
      real_factor =
          Scalar(1) - Scalar(0.5) * theta_sq + Scalar(1.0 / 384.0) * theta_po4;
 }
```

Looks like some kind of Taylor expansion. But I don't understand the reason to use such complex formula in this case.

**Comment by NikolausDemmel** [comment]
For small angles you do a Taylor expansion of the Rodrigues formula, since the latter is numerically unstable (for example the quotient `sin(theta) / theta` for small theta).

Note that this is a Taylor expansion for `theta/2`, which is where additional powers of 2 in the denominators come from. 

Note also, that there is a possible bug, and one of the factors is missing these powers of 2, see https://github.com/strasdat/Sophus/pull/117.

**Comment by strasdat** [comment]
Closing this out. PR #117 addresses the issue @NikolausDemmel found.
