### ISSUE TITLE
issues related to ceres (Jet types)

### ISSUE THREAD

**Issue by ibtaylor** [strasdat/Sophus#116]
Seems like this
https://github.com/strasdat/Sophus/blob/494f4289d1d1c711f97fa48f1d85c551d251fe63/sophus/se3.hpp#L586 
should be something more like
```cpp
Matrix<Scalar, 1, 4>(Scalar(0), Scalar(0), Scalar(0), Scalar(1))
or Matrix<Scalar,1,3>::Zero().homogeneous()
```
Also ran into an issue with
https://github.com/strasdat/Sophus/blob/494f4289d1d1c711f97fa48f1d85c551d251fe63/sophus/so3.hpp#L564
```cpp
> Scalar(0)
```

Does this seem reasonable? I can make a PR if you'd accept these types of changes.

**Comment by NikolausDemmel** [comment]
+1

Shouldn't change the result, and if it fixes Ceres Jet types, the change seems reasonable to me.

**Comment by NikolausDemmel** [comment]
+1

Shouldn't change the result, and if it fixes Ceres Jet types, the change seems reasonable to me.

**Comment by strasdat** [comment]
@ibtaylor @NikolausDemmel Yes, all literals such as ``4`` need to be guarded using ``Scalar(4)``. Please go ahead and open the corresponding PR.

**Comment by strasdat** [comment]
Fixed on master.

**Comment by NikolausDemmel** [comment]
Just a comment, since I came across this again more or less randomly. No need to change anything.

I believe that an alternative for writing `Scalar(1)` everywhere for constants is to use `double` constants, i.e. `1.0`. It seems those convert automatically to for Jet types, whereas other numeric types don't. (caveat: I'm not sure if that works in all situations, and AFAICT there should be no downside of `Scalar(1)` except for maybe code verbosity).
