### ISSUE TITLE
sim3.setScale() is a const method, but shouldn't

### ISSUE THREAD

**Issue by DoubleTwelve** [strasdat/Sophus#12]
It seems there is an issue with setScale method for sim3 transforms.
This method is const and calling this method discards the qualifier.

**Comment by anathan** [comment]
Error	97	error C2662: 'void Sophus::RxSO3GroupBase<Sophus::RxSO3Group<double,0>>::setScale(const double &)' : cannot convert 'this' pointer from 'const Sophus::RxSO3Group<double,0>' to 'Sophus::RxSO3GroupBase<Sophus::RxSO3Group<double,0>> &'	c:\libs\sophus\sophus\sim3.hpp	339	1	lsd_slam

Removing the const constraint (which seems incorrect since it modified this) fixes the problem.

**Comment by jizhou15** [comment]
After removing the const constraint, there is another problem in RxSO3GroupBase::setScale function (rxso3.hpp, line 334):
quaternion() *= scale;  

error C2784: 'Eigen::Quaternion<double,0> &Eigen::QuaternionBase<Eigen::Quaternion<double,0>>::operator *=(const Eigen::QuaternionBase<OtherDerived> &)' : could not deduce template argument for 'const Eigen::QuaternionBase<OtherDerived> &' from 'const double'

Here Scalar = double

Need to change line 334 to:
quaternion() *= Eigen::Quaternion<Scalar>(scale, scale, scale, scale);

**Comment by strasdat** [comment]
Thanks, for reporting. This is fixed now, finally ;)
