### ISSUE TITLE
Sophus scale not positive

### ISSUE THREAD

**Issue by himanshub43** [strasdat/Sophus#18]
Can someone please explain why in rxSo3 constructor (from quaternion) squared norm is compared with epsilon and not zero. I'm frequently getting scaleNotPositive exception because of this.

**Comment by strasdat** [comment]
Hm, yeah, that is no really consistent. The underlying problem is the following:

Mathematically, we have the condition (class invariant) that the scale ``s > 0``. This is necessary, since ``log(0)`` is not defined.

Now, for real numbers is holds that if ``s1 > 0`` and ``s2 > 0`` then ``s1 * s2 > 0``, so the group is closed under multiplication.

However, this is not true for limited precision, e.g.:

```
float a = 1e-32;
float b = 1e-32;
std::cout << "a > 0: " << ((a > 0) ? "True" : "False") << "\n";
std::cout << "b > 0: " << ((b > 0) ? "True" : "False") << "\n";
std::cout << "a * b > 0: " << (((a * b) > 0) ? "True" : "False") << "\n";
```

Outputs:

```
a > 0: True
b > 0: True
a * b > 0: False
```

Thus, currently it is dangerous to have scales which are close to zero. Not sure yet what the best solution to the problem is...

**Comment by strasdat** [comment]
A possible solution would be to have an explicit class invariant that ``q.norm() >= epsilon``. Thus, all constructors/setters will have to ensure this. 

In addition, group multiplication should be implemented with saturation, such as if ``q_mul.norm() < epsilon`` (for ``q_mul := q1 * q2), we renormalize ``q_mul`` such that ``q_mul.norm() = epsilon``.

**Comment by strasdat** [comment]
Pullrequest #36 should fix it.
