### ISSUE TITLE
Question about putting sophus type in stl container

### ISSUE THREAD

**Issue by versatran01** [strasdat/Sophus#188]
can we just put SE3 into std::vector? Looks like in the test it is just pushed into a plain vector.
Or do we need to do that eigen alligned allocator thing?
Just want to make sure.

**Comment by NikolausDemmel** [comment]
AFAICT you can put `SE3` objects in `std::vector`, but you have to do "that eigen aligned allocator thing". This should hold for both `float` and `double` as `Scalar` type.

You have to do that for all [vectorizable fixed size eigen types]( https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html), of which `Quaternion` is an example. Since `SE3` has `Quaternion` as member, it [applies also to that](https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html).

Note that for `std::vector` it is not enough to specify an aligned allocator, you also [need to include `<Eigen/StdVector>`](https://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html).

**Comment by versatran01** [comment]
Thanks for the answer. But in the Ceres example, i didn’t see the aligned allocator though?

**Comment by NikolausDemmel** [comment]
Hm... It may be a bug / oversight, maybe @strasdat knows more?

Note that if you don't use the aligned allocator, it may still work, if you are lucky, or for example if your malloc is always returning 16byte aligned memory (e.g. macos).

**Comment by versatran01** [comment]
This is probably just an oversight. Closing.
