### ISSUE TITLE
How to sample uniformly in SO(3)

### ISSUE THREAD

**Issue by qqfly** [strasdat/Sophus#192]
There are serveral realization of SO(3) sampling.

In Sophus, we firstly uniformly sample a point on a sphere (unit rotation axis), then uniformly sample a rotation angle: [Sophus::SO3d::sampleUniform()](https://github.com/strasdat/Sophus/blob/master/sophus/so3.hpp#L711)

But in Eigen, [Eigen::Quaterniond::unitRandom()](https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html#a7da87cda5567ff1e860782d638643868) is based on http://planning.cs.uiuc.edu/node198.html

Besides, in manif, they generate a random tangent space element and expMap to Lie group: [LieGroupBase::setRandom()](https://github.com/artivis/manif/blob/devel/include/manif/impl/lie_group_base.h#L370).

Which sampling is better? Or, why doesn't Sophus use the Eigen's realization?

Besides, I also open a discussion in [Manif](https://github.com/artivis/manif/issues/68#issuecomment-465162896).

**Comment by strasdat** [comment]
The discussion is quite interesting...

**Comment by dllu** [comment]
Any method that uniformly randomly samples from the 4D hypersphere, treated as a unit quaternion, will be a uniformly random element of SO(3) because of the 2-to-1 mapping from unit quaternions to SO(3).

I would be curious to know if the method cited in the Eigen docs is faster than generating a unit quaternion using Marsaglia's method here: http://mathworld.wolfram.com/HyperspherePointPicking.html

It would seem to me that Marsaglia's method might be faster due to avoiding the sin and cos. At any rate it must be faster three calls to `normal` which is currently used. Incidentally, a related method, also due to Marsaglia, is used for [generating pairs of normal-distributed numbers](https://en.wikipedia.org/wiki/Marsaglia_polar_method).

In my experience, rejection sampling is faster than carefully doing sin and cos, for example, [when generating points in a unit disk](https://gist.github.com/dllu/2433300be8159c796139732a8542c60f).

You guys may find the following meme amusing: ![pic](https://pics.dllu.net/file/dllu-sc/b2d3ef2bce.png)

**Comment by jlblancoc** [comment]
+💯  for the meme! 😃

**Comment by UnixJunkie** [comment]
Look this paper:
cf. "Super-Fibonacci Spirals: Fast, Low-Discrepancy Sampling of SO(3)"
by Marc Alexa
Quite simple method.
