### ISSUE TITLE
Sophus::SE3f::rotationMatrix() gives wrong result

### ISSUE THREAD

**Issue by lanfeiying** [strasdat/Sophus#254]
Hi,

Recently when I was using Sophus to update the camera pose, I found this problem:

If I have a global variable `Sophus::SE3f pose`, and a small rotation multiplies `pose` for hundreds of times, the results from `pose.matrix()` is not a rigid transformation any more;

I tried to output the determinant of the rotation matrix of `pose`, it shows the determinant is not `1`

The minimal reproducible example is as below:
```
OS: archlinux
compiler: gcc11
cxx standard: 17
```

```
//main.cpp
#include <sophus/se3.hpp>
#include <sophus/so3.hpp>

#include <iostream>
#include <string>
#include <cmath>
#include <Eigen/Dense>

int main(int argc, char** argv)
{
    Sophus::SE3f pose_se3;
    
    //create rotation from an angle and a vector (z axis)
    float angle = std::stof(argv[1])
    std::cout<<"angle in radiance: "<<angle<<std::endl;
    std::cout<<"angle in degree:   "<<(angle / M_PI) * 180.0f<<std::endl;

    Eigen::Matrix3f R = Eigen::AngleAxisf(angle, Eigen::Vector3f(0.0f, 0.0f, 1.0f)).toRotationMatrix();
    Sophus::SO3f R_so3(R);
    Sophus::SE3f R_se3(R_so3, Eigen::Vector3f(0.0f, 0.0f, 0.0f));

    int loop_num = std::stoi(argv[2]);
    for(int i = 0; i < loop_num; i++)
    {
        Eigen::Matrix4f new_pose = R_se3.matrix() * pose_se3.matrix();
        
        //update pose
        pose_se3 = Sophus::SE3f(new_pose);

        //output the determinant of rotation matrix of pose_se3
        std::cout<<i<<"    det of rotation: "<<pose_se3.rotationMatrix().determinant()<<std::endl;
    }
    
    return 0;
}
```
For this program, use:
```
~$test 0.1 1000
```
to run the test. The first argument is `angle` in radiance, the second argument is loop number;

If I run `test 0.1 1000`, it works fine.

However, if I run `test 0.01745329 1000`, the result is totally wrong.
```
//output
angle in radiance: 0.0174533
angle in degree:   1
0    det of pose: 1
1    det of pose: 1
2    det of pose: 1
...
103    det of pose: 1
104    det of pose: 1
105    det of pose: 1.00001
106    det of pose: 1.00001
107    det of pose: 1.00002
108    det of pose: 1.00004
109    det of pose: 1.00008
110    det of pose: 1.00018
111    det of pose: 1.00039
112    det of pose: 1.0009
113    det of pose: 1.00214
114    det of pose: 1.00532
115    det of pose: 1.01393
116    det of pose: 1.03933
...
351    det of pose: 20.4425
352    det of pose: 20.4425
353    det of pose: 1353.14
354    det of pose: 1353.14
355    det of pose: 1353.14
...
997    det of pose: 6.2577e+29
998    det of pose: 6.2577e+29
999    det of pose: 6.2577e+29
```

The input `0.01745329f` in radiance is equal to `1.0f` degree. 

Can I ask why if the program rotate `pose_se3` with `1` degree for 1000 times, the results is so strange, but if the rotation angle is `0.1` or `1.0` in radiance, the result is normal?

**Comment by lanfeiying** [comment]
I tried a smaller number than `1` degree, I found this problem occurs when it is a small angle.
Is it because of precision? How to avoid it?

**Comment by NikolausDemmel** [comment]
Interesting. Looks like numerical issues with floating point precision, but some strange jumps like

```
352    det of pose: 20.4425
353    det of pose: 1353.14
```

make me wonder if there might also an implementation issue. Not sure if it's significant that it is just shy of 360 deg...

Two wild guess why it might be happening for 1deg but not for 0.1 rad angels:
1. In general my understanding is that numerical issues appear most when you have operands of very different order of magnitudes or also if you subtract very close (but not equal) values. So with the smaller delta rotations this might be happening more.
2. Maybe there are certain angles for the accumulated pose that are problematic, that you "jump over" with the 0.1rad increments, but you hit with the 1deg increments. However, I'd think you would also cover the wide range of angles when you do 1000 0.1rad increments...

One thing I don't understand is why you do the pose operations with matrices, given that Sophus implements this efficiently with the internal quaternion representation. You can try this and see if it is more stable:
```
        //update pose
        pose_se3 = R_se3 * pose_se3;
```

Otherwise, for both versions, you can try to re-normalize the quaternion every iteration (or every n iterations). To my knowledge this is commonly done, e.g. when doing numerical optimization, precisely to avoid the manifold constraints being violated after some time due accumulating numerical errors.

Is this the latest Sophus `master` branch? To me it looks like the SE3 constructor should give an error if the input is not close to orthogonal for the rotation part when given a 4x4 matrix: https://github.com/strasdat/Sophus/blob/593db47500ea1a2de5f0e6579c86147991509c59/sophus/so3.hpp#L472

Btw, your output doesn't match the code here:

```
std::cout<<i<<"    det of rotation: "<<pose_se3.rotationMatrix()<<std::endl;
```

You could additionally check the norm of the quaternion.

**Comment by strasdat** [comment]
@ianfeiying this is a regression, which I believe was introduced some time ago. I always wanted to address it but was thinking of how to create a test case. Thanks for providing it.

The solution is to apply a pade approximation of quaternion normalization after doing a rotation composition. Ill hope to find some time tomorrow to apply the fix...

**Comment by lanfeiying** [comment]
@NikolausDemmel Hi, Thanks very much for your suggestion!
I tested  `pose_se3 = R_se3 * pose_se3` and it works fine!

In summary, it is better to use `pose_se3 = R_se3 * pose_se3` directly instead of `R_se3.matrix() * pose_se3.matrix()`.
There might be some numerical problem when multiplies with 4x4 matrix.
