### ISSUE TITLE
Transform 3D points from world coordinate to camera coordinates

### ISSUE THREAD

**Issue by ghost** [strasdat/Sophus#307]
Hi, I am new to Sophus and need help to write C++ code correctly. 

Suppose I have a 3D point as Eigen::Vector3d which is in world coordinates. And I have a camera whose position is Sophus::SE3. This position is the transformation for 3D points in world coordinates to camera coordinates. How to write c++ code using Sophus to calculate the position of the 3D point in camera coordinates?

**Comment by DmitriyKorchemkin** [comment]
Hi,

There is an operator* for [left] group action on points:
https://github.com/strasdat/Sophus/blob/master/sophus/se3.hpp#L311-L325

**Comment by NikolausDemmel** [comment]
What @DmitriyKorchemkin suggested in code:

```cpp
// point in world frame
Eigen::Vector3d p_w = ...; 

// camera pose (world-to-cam transformation)
Sophus::SE3d T_c_w = ...;

// point in camera frame
Eigen::Vector3d p_c = T_c_w * p_w;
```

**Comment by DmitriyKorchemkin** [comment]
Note that left group action on points does not requires matching scalar types of group element and point, they are only required to be multipliable by each other.

This allows you, for example, omit unnecessary casts to jet type when using with auto-differentiation (for example - with `ceres::Jet`).
Since jet x scalar multiplication is typically significantly faster than jet x jet, omitting the cast will have better performance.
