### ISSUE TITLE
test_ceres_se3  test compiling error

### ISSUE THREAD

**Issue by yuzhangbit** [strasdat/Sophus#73]
The `test_ceres_se3`  test example has a compiling error below when building the Sophus library.
```
Sophus/test/ceres/test_ceres_se3.cpp:119:1:   required from here
/usr/include/eigen3/Eigen/src/Core/IO.h:132:96: error: no matching function for call to ‘ceil(ceres::Jet<double, 7>)’
     return cast<RealScalar,int>(ceil(-log(NumTraits<RealScalar>::epsilon())/log(RealScalar(10))));
                                                                                                ^
/usr/include/eigen3/Eigen/src/Core/IO.h:132:96: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/x86_64-linux-gnu/c++/4.8/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++config.h:426,
                 from /usr/include/c++/4.8/cmath:41,
                 from /usr/local/include/ceres/jet.h:159,
                 from /usr/local/include/ceres/internal/autodiff.h:145,
                 from /usr/local/include/ceres/autodiff_cost_function.h:132,
                 from /usr/local/include/ceres/ceres.h:37,
                 from /home/robot/workspace/lib_sources/Sophus/test/ceres/test_ceres_se3.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:178:1: note: double ceil(double)
 __MATHCALLX (ceil,, (_Mdouble_ __x), (__const__));
 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:178:1: note:   no known conversion for argument 1 from ‘ceres::Jet<double, 7>’ to ‘double’
```
###  Environment 
* ubuntu 14.04.5 x64

**Comment by strasdat** [comment]
Yeah, currently Sophia+Ceres together only works with a specific version of Eigen.

The underlying issue is that Ceres:Jet types don't play very nicely together with Eigen:Matrix when it comes to insertion overloads "std::ostream operator<<".  In particular, Sophia relies on some internal API of Eigen to print Eigen::Matrix<Jet<...>>. Obviously, relying on Eigen's internal API is not ideal, since it changes quite significant between different Eigen versions.

I will look into this, but it'll take me a couple of weeks or so...

**Comment by strasdat** [comment]
Can you try it with Eigen 3.3.3 and the latest version of Ceres (from the master branch)? This should work. 

I will add Ceres to Travis CI soon.

**Comment by yuzhangbit** [comment]
@strasdat  Thank you very much.  Will do it and provide the feedback soon.

**Comment by yuzhangbit** [comment]
+1 . It works.
