### ISSUE TITLE
Does Sophus class support std::move in C++11 ?

### ISSUE THREAD

**Issue by SkyRiderMike** [strasdat/Sophus#87]

**Comment by jlblancoc** [comment]
You can use [these guys](http://en.cppreference.com/w/cpp/types/is_move_constructible) inside an `static_assert();` to test it... 

Example of use [here](http://stackoverflow.com/a/7055102/1631514).

**Comment by strasdat** [comment]
All core classes should have implicitly-declared [move constructors and move assignment operators](http://en.cppreference.com/w/cpp/language/move_constructor).

However, since the Sophus classes are merely wrappers around **fixed-size** Eigen vectors, all such moves are basically copies.

Obviously, nothing would stop you to create dynamically allocated entities such as ``std::unique_ptr<SE3d>`` or ``std::vector<SO3f>`` and move them efficiently.
