### ISSUE TITLE
sim(2) implementation

### ISSUE THREAD

**Issue by pinglin** [strasdat/Sophus#92]
Have been off-focus of Sophus for a while and it seems that it has been updated quite a bit. 
@strasdat are you still gonna add sim(2) functionality? If so, the very old non-merged PR #9 is now outdated though. I would like to use the up-to-date Sophus while my current project needs a sim(2) transformation still. Do you consider to help add or review the sim(2) if I send a PR again? Thanks.

**Comment by strasdat** [comment]
Hey, I'm working on a sim(2) implementation at the moment. Will post an update in the next couple of weeks.

**Comment by strasdat** [comment]
I opened a corresponding PR: #95. 

Thanks for sharing the initial implementation (some years ago), and apologies that I did not address this feature earlier. Since the API/funcionality changed quite a bit, it was easier for me to base RxSO2/SIm2 on the current version of RxSO2/Sim3 instead of your initial PR.

**Comment by strasdat** [comment]
Merged into master, closing this out.
